#!/bin/sh

#
# time_multiply
#
# Run multiply and square timing tests, to compute a chart for the
# current processor and compiler combination.
#
# by Michael J. Fromberger <sting@linguist.dartmouth.edu>
# Copyright (C) 2000 Michael J. Fromberger, All Rights Reserved
#
# $Id: time_multiply,v 1.1 2004/02/08 04:28:33 sting Exp $
#

ECHO=/bin/echo

$ECHO ""
$ECHO "** Running multiply and square timing tests"
$ECHO ""

$ECHO "Bringing 'mulsqr' up to date ... "
if make mulsqr ; then
    :
else
    $ECHO ""
    $ECHO "Make failed to build mulsqr."
    $ECHO ""
    exit 1
fi

if [ ! -x ./mulsqr ] ; then
    $ECHO ""
    $ECHO "Cannot find 'mulsqr' program, testing cannot continue."
    $ECHO ""
    exit 1
fi

sizes='64 128 192 256 320 384 448 512 640 768 896 1024 1536 2048'
ntests=500000

$ECHO "Running timing tests, please wait ... "

trap 'echo "oop!";rm -f tt*.tmp;exit 0' INT HUP

touch tt$$.tmp
$ECHO $ntests tests >> tt$$.tmp
for size in $sizes ; do
    $ECHO "$size bits ... \c"
    set `./mulsqr $ntests $size|head -3|tr -d '%'|awk '{print $2}'`
    $ECHO $size"\t"$1"\t"$2"\t"$3 >> tt$$.tmp
    $ECHO "(done)"
done
mv tt$$.tmp mulsqr-results.txt
rm -f tt$$.tmp

exit 0
