#!/bin/sh

VERS="1.8.6"
SECT="1"
NAME="MPI Tools"

echo "Building manual pages ..."
case $# in
  0)
    files=`ls *.pod`
    ;;
  *)
    files=$*
    ;;
esac

for name in $files
do
   echo -n "$name ... "
   sname=`noext $name`
   pod2man --section="$SECT" --center="$NAME" --release="$VERS" $name > $sname.$SECT
   echo "(done)"
done

echo "Finished building."

